name: build

on:
  push:
    # Don't run if we didn't change any code or environment definitions
    paths-ignore:
      - '**/*.md'  # ignore docs updates
      - 'k8s/**/*.yml'  # ignore changes to job definitions
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "kingb12"  # Note: modify this if copying
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Nautilus Gitlab Docker Registry
        uses: docker/login-action@v2
        with:
          registry: gitlab-registry.nrp-nautilus.io
          username: "kingb12"  # Note: modify this if copying
          password: ${{ secrets.GITLAB_DOCKER_REGISTRY_TOKEN }}
      - 
        name: temp clean stuff
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: k8s/Dockerfile
          tags: |
            kingb12/hf_libraries_demo:latest
